### ISSUE TITLE
Неправильная позиция контекстного меню если есть два монитора с разным разрешением

### ISSUE THREAD

**Issue by vitsum** [AnimeLore/cucumber-timer#3]
Основной экран 4к, дополнительный 1080p
Открываю окно настроек, переношу на дополнительный экран.
Теперь правой кнопкой кликаю по иконке в трее и контекстное меню появляется в середине экрана

https://pasteboard.co/2BGUMxqy5ZRP.png

**Comment by AnimeLore** [comment]
проблема скорее всего связана с winforms/самой ОС. в коде программы нет контроля местоположения контекстного меню
